### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by pendex900x** [tomcastro/licensePlateDatasetGenerator#1]
Hello, what python version do you use to run it?
I have this error:

```
py -2 randomPlateGenerator.py

Traceback (most recent call last):
  File "randomPlateGenerator.py", line 75, in <module>
    randomPlateGenerator(style=style, reps=reps)
  File "randomPlateGenerator.py", line 26, in randomPlateGenerator
    os.makedirs(os.path.join(dirpath, 'data', 'labels'), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```

And if I run it with python 3:

```
py -3 randomPlateGenerator.py

Traceback (most recent call last):
  File "randomPlateGenerator.py", line 75, in <module>
    randomPlateGenerator(style=style, reps=reps)
  File "randomPlateGenerator.py", line 58, in randomPlateGenerator
    numberToImage(licensePlate, style)
  File "C:\Users\X\Desktop\licensePlateDatasetGenerator-master\licensePlateDatasetGenerator-master\numberToImage.py", line 48, in numberToImage
    text += getBoundingBoxes(canvas_cp, lp, xoffset=20, yoffset=20)
  File "C:\Users\X\Desktop\licensePlateDatasetGenerator-master\licensePlateDatasetGenerator-master\numberToImage.py", line 88, in getBoundingBoxes
    im2, cnts, h = cv2.findContours(thresh, 1, 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

Do you know what can be the problem?

**Comment by radzinger** [comment]
im2, cnts, h = cv2.findContours(thresh, 1, 2) remove im2 --> cnts, h = cv2.findContours(thresh, 1, 2)
